# .streamlit/secrets.toml
# 로컬 MariaDB
DB_HOST = "localhost"
DB_PORT = "3306"
DB_USER = "root"
DB_PASSWORD = "1234"
DB_NAME = "music_chart"
DB_SSL = "false"

# Aiven 사용 시 아래로 교체
# DB_HOST = "mysql-22039057-musicproject1.c.aivencloud.com"
# DB_PORT = "25918"
# DB_USER = "avnadmin"
# DB_PASSWORD = "your_aiven_password_here"
# DB_NAME = "music_chart"
# DB_SSL = "true"
